name = "bargh-manager"
main = "src/index.js"
compatibility_date = "2026-07-01"

kv_namespaces = [
  { binding = "BARGH_KV", id = "83ad4a4fc7dd4e1383c8dc2342ef6554" }
]

[triggers]
crons = ["*/2 * * * *", "*/30 * * * *"]
